spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/review_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

internal:
  service-token: ${REVIEW_SERVICE_TOKEN}